project:
  type: website
  output-dir: docs
  preview: 
    port: 7777

website:
  title: "Santi Montiel"
  favicon: "images/robot.png"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/santimontiel
      - icon: twitter
        href: https://twitter.com/santimontieleu
      - icon: linkedin
        href: https://www.linkedin.com/in/santiago-montiel-mar%C3%ADn/

format:
  html:
    theme: darkly
    css: styles.css

